name: keepalived
adopt-info: keepalived
summary: High availability VRRP and load-balancing for Linux
description: |
  Keepalived provides simple and robust loadbalancing and high-availability
  to Linux based infrastructures using VRRP and the well-known Linux Virtual
  Server (IPVS) kernel module.

grade: stable
confinement: classic

apps:
  daemon:
    daemon: forking
    command: usr/sbin/keepalived
  keepalived:
    command: usr/sbin/keepalived
  genhash:
    command: usr/bin/genhash

parts:
  linux-headers:
    plugin: dump
    source: http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-161.211_amd64.deb
    override-build: |
      snapcraftctl build
      # Move the headers on the host out of the way
      mv /usr/include/linux /opt/linux || true
      # Move header from the part to the host
      mv usr/include/linux /usr/include/  || true
    stage:
      - -*
    prime:
      - -*

  keepalived:
    plugin: autotools
    source: .
    source-type: git
    after:
      - linux-headers
    configflags:
      - --prefix=/usr
      - --enable-bfd
      - --enable-dbus
      - --enable-json
      - --enable-regex
      - --enable-snmp
      - --enable-snmp-rfc
      - --disable-libipset-dynamic
    override-build: |
      snapcraftctl build
      VER=$(grep GIT_COMMIT lib/git-commit.h | cut -d'"' -f2)
      snapcraftctl set-version $VER
    build-packages:
      - iptables-dev
      - libipset-dev
      - libjson-c-dev
      - libglib2.0-dev
      - libmagic-dev
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnfnetlink-dev
      - libpcre2-dev
      - libsnmp-dev
      - libssl-dev
    stage-packages:
      - libnfnetlink0
      - libipset3
      - libjson-c2
      - libglib2.0-0
      - libmagic1
      - libnl-3-200
      - libnl-genl-3-200
      - libpcre2-8-0
      - libsnmp30
